#!/bin/bash

export OPENAI_API_KEY=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
export ELASTIC_UNAME=elastic
export ELASTIC_PWD=0X=+wWfc5F1gHZ3++K8c

# Default mode
MODE_Q_V="verbose"
TEXT_ARG=""
PWD=$(pwd)

# Function to print help
print_help() {
    echo "Usage: hey [OPTIONS]"
    echo "Options:"
    echo "  -q, --quiet   Cut out pre-explanation and only give the command."
    echo "  -v, --verbose Default mode. Give the pre-explanation before the command."
    echo "  -t, --text    Text mode. Query is provided in the form of text rather than voice. Requires an argument."
    echo "  -h, --help    Display this help menu."
}

# Process command-line options
ARGS=$(getopt -o qvht: --long quiet,verbose,text:,help -n "hey" -- "$@")

if [ $? -ne 0 ]; then
    echo -e "\033[0;31mInvalid option used: $1\033[0m"
    print_help
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
        -q|--quiet)
            MODE_Q_V="quiet"
            shift
            ;;

        -v|--verbose)
            MODE_Q_V="verbose"
            shift
            ;;

        -t|--text)
            MODE="text"
            TEXT_ARG="$2"
            shift 2
            ;;

        -h|--help)
            print_help
            exit 0
            ;;

        --)
            shift
            break
            ;;

        *)
            echo -e "\033[0;31mInvalid option used: $1\033[0m"
            print_help
            exit 1
            ;;
    esac
done

#INCLUDE THE PYTHON SCRIPT
python /home/onese/Desktop/PROJO/VOICE_24/hey.py "$PWD" "$MODE_Q_V" "$MODE" "$TEXT_ARG"
